version: "3.8"

services:
  app:
    image: ${DOC_USER}/${PROJECT}
    container_name: ${PROJECT}
    ports:
      - "80:5000"
    restart: always
    environment:
      - ConnectionStrings__DefaultConnection=${DB_SECRETS}
      - JWT:Key=${JWT_KEY}
      - JWT:Issuer=${JWT_ISSUER}
      - JWT:Audience=${JWT_AUDIENCE}
      - EmailConfigurations:Email=${EC_EMAIL}
      - EmailConfigurations:Password=${EC_PASSWORD}
      - EmailConfigurations:Host=${EC_HOST}
      - EmailConfigurations:DisplayName=${EC_DISPLAY_NAME}
      - EmailConfigurations:Port=${EC_PORT}
    depends_on:
      - postgres
    networks:
      - web
    volumes:
      - ./${PROJECT}-app-data:/App/wwwroot/Images

  postgres:
    image: postgres
    container_name: ${PROJECT}-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${PG_PW}
      POSTGRES_USER: ${PG_USER}
    networks:
      - web
    volumes:
      - ./${PROJECT}-db-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgAdmin4
    restart: always
    user: '$UID:$GID'
    ports:
      - "${PGC_PORT}:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGC_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGC_PASSWORD}
      PGADMIN_LISTEN_ADDRESS: 0.0.0.0
    depends_on:
      - postgres
    networks:
      - web
    volumes:
      - ./${PROJECT}-pg-data:/var/lib/pgadmin

networks:
  web:
    external: true
    driver: bridge